export const Strings = {
  NOTIFICATIONS: "Notifications",
  NEWS: "News",
  JOBS: "Jobs",
  REFERRALS: "Referrals",
  RECRUITER: "Recruiter",
  EMAIL_USERNAME: "Email Address / Username",
  PASSWORD: "Password",
  LOGIN: "Login",
  CREATE_ACCOUNT: "CREATE ACCOUNT",
  API_ERROR: "Something went wrong, try again after sometime",
  EMPTY_EMAIL_USERNAME: "Please enter email address or username",
  EMPTY_PASS: "Please enter password",
  REGISTER: "Register",
  ACCOUNT_INFORMATION: "Account Information",
  STEP_ONE_OF_THREE: "Step 1 of 3",
  STEP_TWO_OF_THREE: "Step 2 of 3",
  STEP_THREE_OF_THREE: "Step 3 of 3",
  CONTACT_INFO: "Contact Information",
  AVAILABILITY_AND_POSITION: "Availability & Position",
  FIRST_NAME: "First Name",
  ENTER_FIRST_NAME: "Please enter first name",
  LAST_NAME: "Last Name",
  ENTER_LAST_NAME: "Please enter last name",
  FIRST_LAST_NAME_SAME_ERROR: "First and Last names cannot be the same",
  EMAIL: "Email Address",
  ENTER_EMAIL: "Please enter email address",
  EMAIL_ALREADY_USED: "Sorry, that email has already been used!",
  INVALID_EMAIL: "Invalid email address",
  PASS_MIN_LENGTH: "Must be at least 5 characters",
  CONFIRM_PASS: "Confirm Password",
  PASS_NOT_MATCH: "Passwords do not match",
  SIGN_UP: "Sign Up",
  PHONE: "Phone",
  ENTER_PHONE: "Please enter phone",
  PHONE_MIN_LENGTH: "Must be at least 10 digits",
  PHONE_TYPE: "Phone Type",
  SELECT_PHONE_TYPE: "Please select phone type",
  BEST_TIME_TO_CALL: "Best Time to Call",
  SELECT_BEST_TIME_TO_CALL: "Please select best time to call",
  ANYTIME: "Anytime",
  IMMEDIATELY: "Immediately",
  MORNING: "Morning",
  AFTERNOON: "Afternoon",
  EVENING: "Evening",
  AVAILABILITY_DATE: "Availability Date",
  SELECT_AVAILABILITY_DATE: "Please select availability date",
  DISCIPLINE: "Discipline",
  SELECT_DISCIPLINE: "Please select discipline",
  REFERRED_BY: "Were You Referred by a TRS Nurse?",
  SELECT_REFERRED_BY: "Please select were you referred by a TRS Nurse?",
  YES: "Yes",
  NO: "No",
  HOW_YOU_HEAR_ABOUT_US: "How did you hear about us?",
  SELECT_HOW_YOU_HEAR_ABOUT_US: "Please select how did you hear about us?",
  REFERRER_NAME: "Referrer's Name",
  ENTER_REFERRER_NAME: "Please enter Referrer's Name",
  CONTINUE: "Continue",
  CANCEL: "Cancel",
  RETRY: "Retry",
  MY_NOTIFICATIONS: "My Notifications",
  ALL_CAUGHT_UP: "You're all caught up!",
  NO_DATA_NOTIFICATIONS:
    "We'll let you know when something new requires your attention.",
  CREDENTIAL_DROPBOX: "CREDENTIALS DROPBOX",
  UPDATE_PROFILE_PHOTO: "UPDATE PROFILE PHOTO",
  REWARDS_REDEMPTION: "REWARDS & REDEMPTION",
  JOB_PREFERENCE: "JOB PREFERENCES",
  LOGOUT: "LOGOUT",
  APP_VERSION: "v2.0.3",
  PRIVACY_POLICY: "Privacy Policy (Website)",
  UNABLE_TO_FIND_APP: "Unable to find app in which to open privacy policies",
  TAKE_PICTURE: "Take a picture",
  CHOOSE_FROM_PHOTO_LIBRARY: "Choose from photo library",
  GIVE_CAMERA_PERMISSION: "Give Camera permission from settings",
  CREDENTIALS: "Credentials",
  UPLOAD_CREDENTIALS_DOCUMENT: "Upload Credentials Document",
  ARE_YOU_SURE: "Are you sure?",
  ITEM_REMOVE_PERMANENT: "Item will be removed permanently.",
  DELETE: "Delete",
  MY_RECRUITER: "My Recruiter",
  ACTIONS: "Actions",
  CALL: "CALL",
  MESSAGES: "MESSAGES",
  MESSAGE: "MESSAGE",
  NO_RECRUITER:
    "You currently have no recruiter assigned. To reach a recruiter, please click the button below.",
  SPEAK_RECRUITER: "Speak With a Recruiter",
  REFER_FRIEND: "REFER A FRIEND!",
  REFERRAL_ACTIVITY: "Referral Activity",
  NEED_EXTRA_INCOME: "Need Extra Income?",
  EXTRA_INCOME_PHRASE:
    "It has never been so easy. Refer your\nfriends or colleagues and then sit back and\nwatch the money float in.",
  THOUSAND_DOLLAR: "$1000",
  REFERAL_BONUS_STRING_ONE: " referral bonus for you when you refer an RN and ",
  TWO_FIFTY_DOLLAR: "$250",
  REFERAL_BONUS_STRING_TWO: " for them. LPN/Tech bonuses are also available.",
  REFER_A_FRIEND_TODAY: "Refer a Friend Today!",
  PERSONAL_MESSAGE: "Personal Message",
  NEW_REFERRAL_POLICY:
    'By clicking "Send" you are giving TRS Healthcare consent to send this person e-mail and / or text messages letting them know that you have referred them. Standard text messaging rates will apply.',
  SEND: "Send",
  NEW_REFERRAL: "New Referral",
  MY_JOBS: "My Jobs",
  CURRENT: "CURRENT",
  OFFERS: "OFFERS",
  SUBMITTED: "SUBMITTED",
  FIND: "FIND",
  PENDING_OFFERS: "PENDING OFFERS",
  PENDING_CONTENT:
    "The following offers are pending your approval! Contact your recruiter today for more information.",
  FEEDBACK_NEEDED: "Feedback Needed",
  NOT_INTERESTED: "Not Interested",
  ASSIGNMENT: "Assignment",
  UNSURE: "Unsure",
  INTERESTED: "Interested",
  APPLICATION_SUBMITTED: "Applications Submitted",
  SUBMITTED_CONTENT:
    "Your application was recently submitted to the following health care providers.",
  SUBMITTED_APPLICATION: "Submitted Application",
  SUBMISSION_DETAILS: "SUBMISSION DETAILS",
  OFFER_DETAILS: "OFFER DETAILS",
  MY_RECRUITER_CAPS: "MY RECRUITER",
  CALL_SMALL: "Call",
  SEND_MESSAGE: "Send Message",
  PENDING_OFFER: "Pending Offer",
  WHAT_DO_YOU_THINK: "What Do You Think?",
  FEEDBACK_DETAILS:
    "Based on the initial details above, are you interested in this offer?",
  COMMENTS: "Comments",
  OPTIONAL: "(Optional)",
  SEND_FEEDBACK: "Send Feedback",
  NO_DATA_CURRENT:
    "We'll let you know when something new requires your attention",
  TIMESHEETS: "Timesheets",
  LATE: "Late",
  NO_TIMESHEETS:
    "Your time sheets are not managed through TRS Healthcare, to fill out your time sheets please click",
  HERE: " here.",
  CONTRACT_DETAILS: "Contract Details",
  NEW_MESSAGE: "New Message",
  EMPTY_MESSAGE: "Please enter message",
  ACTION_REQUIRED: "Action Required",
  JOB_SHARED: "Job Shared",
  MATCH: "Match",
  NOT_INTERESTED: "Not Interested",
  SUBMIT_ME: "Submit Me",
  JOB_DETAILS: "Job Details",
  HELP_US_GET_BETTER: "Help us get better!",
  WHICH_ASPECT_NOT_LIKE: "Which aspects of this job did you not like?",
  COMMENT: "Comment",
  ENTER_COMMENT: "Please enter comment",
  NO_ASPECTS: "No Aspects?",
  SELECT_ASPECT: "Please select any aspect or add comment",
  DECLINE_ERROR: "Declination error",
  SOMETHING_WRONG_DECLINE:
    "There was an issue declining this submission. Try again or restart your app.",
  LOOKING_FOR_JOB: "Looking for a new job?",
  FILL_PREFERENCE:
    "Find jobs uniquely suited to you by\nfilling out your job preferences!",
  SUBMISSION_CONFIRMATION: "Submission Confirmation",
  TIME_OFF: "TIME OFF",
  TIME_OFF_DESC_ONE: "Enter any time off needed during this assignment.\n(",
  TIME_OFF_DESC_TWO: " - Pending start date confirmation)",
  ENTER_TIME_OFF:
    "Time off is required for submission. If you have no time off during this time period, please type None",
  CONTACT_TIME: "BEST TIME TO CONTACT",
  OTHER_CONSIDERATIONS: "OTHER CONSIDERATIONS",
  ACKNOWLEDGEMENT: "ACKNOWLEDGEMENT",
  ACKNOWLEDGEMENT_SMALL: "Acknowledgement",
  ACKNOWLEDGEMENT_ERROR:
    "You must agree to the terms above before clicking submit.",
  ADD_COMMENTS: "+ Add comments (optional)",
  BEST_TIME_LABEL:
    "What is the best time to contact you for a potential interview?",
  RELEVANT_INFO_LABEL:
    "What other relevant information do we need to know about?",
  ACKNOWLEDGEMENT_LABEL:
    'By clicking "submit" below I understand and agree with the following:',
  TERMS_AND_CONDITIONS_LABEL:
    "Given the details presented to me in this job notification, I would accept this position if offered, assuming details about this position do not change another offer is not accepted prior to this position.",
  SUBMIT: "Submit",
  GO_BACK: "Go Back",
  SUBMISSION_ERROR: "Submission Error",
  TRY_AGAIN_RESTART:
    "There appears to be an issue submitting your confirmation. Try again or restart your app.",
  JOB_PREFERENCES: "Job Preferences",
  PREFERENCE_TEXT:
    "Indicate your preference for each of the following categories and rank them based on your order of importance.",
  NEXT: "NEXT",
  PREPARING: "PREPARING ...",
  PREVIOUS: "PREV",
  PREFERENCE_PAY: "What is your minimum desired weekly gross pay?",
  MORE_JOBS: "More Jobs",
  AVERAGE: "Average",
  FEWER_JOBS: "Fewer Jobs",
  LOCATION: "Location",
  PAY: "Pay",
  OKAY: "Okay",
  DONE: "Done!",
  SUCCESS_SUBMIT_ME:
    "One of our trusty account managers will do a final check on this job's minimum requirements before submitting your profile. We will keep you posted.",
  FEEDBACK_SUBMIT_SUCCESS: "Feedback submitted successfully",
  ERROR: "Error",
  SPECIALTIES: "Specialties",
  EMPTY_SPECIALITIES:
    "Specialties are based on your work history. Please visit our website to complete a full application and complete your work history.",
  SHIFT: "Shift",
  DURATION: "Duration",
  PREFERENCE_DURATION_TEXT:
    "How many weeks do you want to work on your next assignment?",
  START_DATE: "Start Date",
  FINISH: "Finish",
  START_DATE_TEXT: "What is your earliest available start date?",
  AVAILABLE_DATE: "Available Date : ",
  DEATIL_LOCATION_SELECTION: "Detail Location Selection",
  CONFIRM: "Confirm!",
  CLEAR_MAP_SHAPES: "Are you sure you would like to clear all map shapes?",
  CLEAR: "Clear",
  DONT_CLEAR: "Don't Clear",
  LATE: "Late",
  SHIFT_TYPE: "Shift Type",
  UNIT: "Unit",
  TIME_IN: "Time In",
  TIME_OUT: "Time Out",
  LUNCH_TIME: "Lunch (Minutes)",
  SAVE: "Save",
  NEW_SHIFT_ENTRY: "New Shift Entry",
  SHIFT_DATE: "Shift Date",
  MORE: "MORE",
  SUBMIT_WITH_NO_TIME: "SUBMIT WITH NO TIME",
  SIGN_AND_SUBMIT: "SIGN & SUBMIT",
  TIME_SHEET_MODAL_TITLE_NO_TIME: "Submit Timesheet with No Time?",
  TIME_SHEET_MODAL_TITLE: "Submit Timesheet?",
  TIME_SHEET_MODAL_MSG:
    "You are signing your time sheet and are agreeing that all of the information provided is accurate to the best of your knowledge.",
  SIGNED_TIME_SHEET_ACTIONS: "Signed Timesheet Actions",
  VIEW_TIME_SHEET: "View Timesheet",
  TAKE_A_PICTURE: "Take a Picture",
  UPLOAD_SIGNED_TIME_SHEET: "Upload Signed Timesheet",
  DOWNLOAD_SIGNED_TIME_SHEET: "Download Signed Timesheet",
  CANCEL: "Cancel",
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
  THANK_YOU: "Thank You!",
  JOB_PREFERENCES_SUCCESS_TEXT:
    "We have already started grading jobs based on your preferences. We'll let you know when they are ready for you to review!",
  JOB_PREFERENCES_FAILURE_TEXT:
    "Thank you for providing a majority of your preferences. Please work with your recruiter to update any licenses/certifications or work history so that you can complete your preferences and begin receiving job matches.",
  RM_SHIFT_DATE_TITLE: "Shift has no date selected",
  RM_SHIFT_DATE_MSG: "Shift date should be selected",
  RM_SHIFT_TYPE_TITLE: "Shift type missing",
  RM_SHIFT_TYPE_MSG: "Shift type should be selected",
  RM_LUNCH_TIME_TITLE: "Lunch time is missing",
  RM_LUNCH_TIME_MSG: "Lunch time can't be empty",
  RM_NO_HOURS_TITLE: "Shift has no hours worked",
  RM_NO_HOURS_MSG: "Shift cannot be zero hours",
  RM_TOTAL_HOURS_TITLE2: "Shift is less than 2 hours",
  RM_TOTAL_HOURS_TITLE15: "Shift is greater than 15 hours",
  RM_TOTAL_HOURS_MSG15: "Are you sure you want to save this shift?",
  OOPS_TEXT: "Oops! something went wrong.",
  TRY_AGAIN_TEXT: "Please try again!",
  OOPS: "Oops!",
  REDEMPTION_CENTER: "Redemption Center",
  REWARDS_AWARDED: "Rewards Awarded:",
  REWARDS_REDEEMED: "Rewards Redeemed:",
  REWARDS_AVAILABLE: "Rewards Available:",
  GET_SPECIAL: "Get Special",
  REWARDS_MODAL:
    "points will be deducted from your available points. Please confirm below.",
  NEEDS: "Needs",
  MORE_POINTS: "more points to redeem item.",
};
